### ISSUE TITLE
Patch help file as easy way to patch the deployment.

### ISSUE THREAD

**Issue by eyenx** [adfinis-sygroup/debug-container#5]
https://github.com/adfinis-sygroup/debug-container/pull/4#discussion_r458687924

**Comment by eyenx** [comment]
We can describe this modification of the deployment using a [patch file](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/):

```yaml
# debug-patch.yml
---

spec:
  template:
    spec:
      containers:
      - name: debug
        image: adfinissygroup/debug:latest
```

Apply with: `kubectl patch deployment web --patch "$(cat debug-patch.yml)"`

We could add this as an additional help text to quickly patch existing deployments?b
